version: '3.9'

services:
  postgres-db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports:
      - '54320:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - internal

  app:
    container_name: golang_container
    environment:
      - DB_USER=postgres
      - DB_PASSWD=postgres
    build: .
    ports:
      - '8081:8080'
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgres-db
    networks:
      - internal

networks:
  internal:
    driver: bridge